### ISSUE TITLE
Cannot resolve the name 'MailListenerCumulativeAttributeGroup' to a(n) 'attribute group' component

### ISSUE THREAD

**Issue by jacodg** [ibissource/frank-doc#101]
When using FrankConfig.xsd in VSCode with F!F 7.8-20220401.105103 the following is shown when hovering FrankConfig.xsd:

There are '2' errors in 'FrankConfig.xsd'.xml
[FrankConfig.xsd(7649, 28): ]()src-resolve: Cannot resolve the name 'MailListenerCumulativeAttributeGroup' to a(n) 'attribute group' component.

**Comment by mhdirkse** [comment]
Should have been fixed by #102 and #103.
