### ISSUE TITLE
If a non-interface class is config child, there is an error if it is @Protected

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/frank-doc#121]
Assume that some class Container has a config child setter with argument type Child. Child is not an interface and it has annotation @Protected. These classes are invalid input to the Frank!Doc doclet, because there is no XML tag allowed for the config child setter. The doclet should produce an error for this kind of input and the build should fail.

**Comment by gvanbrakel** [comment]
I am not convinced that this should result in an error or failure

**Comment by mhdirkse** [comment]
I discussed with @gvanbrakel on the phone. If a protected class appears as the argument of a method, then that method should not be a config child setter. This feature is handy to reduce the number of annotations needed. Assume that many classes have a registerReceiver method that takes an argument of type Receiver. If we can omit the config children by annotating class Receiver with a protected annotation, then that annotation is not needed on the registerReceiver methods.
