### ISSUE TITLE
TransactionAttribute not seen in FrankDoc

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#13]
**Describe the issue**
Most Pipes derive from AbstractPipe, that derives from TransactionAttributes. That has an attribute 'transactionAttribute', that is not seen in the Frank!Doc.

**Reporter**
Gerrit

**To Reproduce**
1. Go to Ibis4Example
2. Click on FrankDoc
3. Select a Pipe
4. See no transactionAttribute attribute

**Environment**
```
FF! 7.7-SNAPSHOT: Ibis4Example
Running on vlapp05.interpar.nl using Apache Tomcat/7.0.90
Java Version: OpenJDK Runtime Environment (1.8.0_242-b08)
Heap size: 165M, total JVM memory: 1103M
Free disk space: 11GB, total disk space: 17GB
Up since: 2021-10-12 18:21:25 (14h)
```

**Comment by mhdirkse** [comment]
Ik heb een fix gemaakt: https://github.com/ibissource/frank-doc-plugin/pull/1

**Comment by mhdirkse** [comment]
Het werkt op mijn lokale PC. Ik kon het niet op de server testen.

**Comment by mhdirkse** [comment]
Het probleem is opgelost en we snappen wat er aan de hand was. De Frank!Doc kan niet met Lombok @Getter en @Setter annotaties overweg. Daarom moet dit doclet gevoed worden met Java classes waar deze annotaties niet inzitten. Er is een Maven plugin "lombok-maven-plugin" die de sources kopiëert en die daarbij de @Getter en @Setter annotaties vervangt door Java methods. We hebben de "maven-javadoc-plugin" geforked zodat hij de de-lombok-te code gebruikt bij elk subproject. Deze fork is de "frank-doc-plugin". We gebruiken dus niet de "maven-javadoc-plugin" om de Frank!Doc doclet te draaien maar de "frank-doc-plugin".

Er zat een fout in de "frank-doc-plugin" waardoor hij onverwachts de originele source code las. Daardoor hebben we attributes gemist die met een Lombok @Setter gedefiniëerd worden. Deze bug is verholpen met twee PRs op ons frank-doc-plugin project: https://github.com/ibissource/frank-doc-plugin/pull/1 en https://github.com/ibissource/frank-doc-plugin/pull/2.
