### ISSUE TITLE
Frank!Doc: Remove javadoc tags in XSD

### ISSUE THREAD

**Issue by nielsm5** [ibissource/frank-doc#14]
**Describe the issue**
Documentation is added to the xsd elements, just like in the JSON. However in the XSD you sometimes still see `{@link Receiver Receivers}` it should remove the text between the `{@`..` }` but keep the last word.
eq;
`{@link Receiver Receivers}` --> `Receivers`
`{@link Receiver}` --> `Receiver`

**Comment by mhdirkse** [comment]
Werken de {@link ... } constructies wel in de web applicatie? Moet daar niet hetzelfde gebeuren als wordt voorgesteld voor de XSDs?

**Comment by nielsm5** [comment]
Dit werkt al in de webapplicatie.
