### ISSUE TITLE
Setting a '@Default' annotation on an overridden method does not always work

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#140]
The @Default annotation set on an overridden setter does not always provide the expected result.
See https://frankdoc.frankframework.org/#!/Listeners/MessageStoreListener.
The attribute tableName has the right default, but that has also a '@Optional' annotation.
attributes keyField and messageField do not have the right default displayed.

**Comment by mhdirkse** [comment]
Documentation of @ff.ref in iaf project is in the following PR: https://github.com/ibissource/iaf/pull/4082
