### ISSUE TITLE
IbisDoc or JavaDoc for ConfigChild-setters in interfaces is not seen in FrankDoc

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#17]
**Describe the issue**
IbisDoc or JavaDoc for ConfigChild-setters in interfaces is not seen in FrankDoc

**Reporter**
Gerrit

**To Reproduce**
1. Go to FrankDoc of AbstractPipe, e.g. via FixedResult
2. See that Locker has no documentation
3. See that Locker is documented in IExtendedPipe

**Comment by nielsm5** [comment]
Duplicate of #13

**Comment by mhdirkse** [comment]
The Frank!Doc wrapper API has methods to get JavaDocs and annotations from implemented interfaces. That logic does not apply filtering. This means that we may find JavaDocs that are not in nl.nn.... packages. I will not take measures to prevent this from happening. If we ever discover documentation in the Frank!Doc that we do not want, then it may be time to do something.

**Comment by mhdirkse** [comment]
Ah, nu zie ik dat Niels dit als een duplicate heeft aangemerkt. Voor dat andere issue, over transactionAttribute, heb ik een fix gemaakt. Inderdaad treedt het issue op mijn lokale PC niet op. Daar staat die fix.

**Comment by mhdirkse** [comment]
![javaDocsAreFoundFromInterfaces](https://user-images.githubusercontent.com/6784732/139716228-a699c11a-2fb6-44f0-92c1-3e05bef591cb.jpg)

**Comment by mhdirkse** [comment]
Om deze figuur te maken moest ik de JavaDoc van AbstractPipe.setLocker() weghalen.

**Comment by mhdirkse** [comment]
Ik schreef over filtering. Ik heb een PR gemaakt die test dat het waar is wat ik schreef: https://github.com/ibissource/frank-doc/pull/19
