### ISSUE TITLE
attribute 'active' appears too many times

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#20]
In the FrankDoc.xsd, every element contains a reference to attribute 'active'. 
It would be more efficient if child elements would inherit this from their hierarchical parent.

**Comment by mhdirkse** [comment]
Attribute active wordt al gemaakt als een verwijzing. Dit is dus heel weinig tekst per element. Is het de moeite waard om dit te optimaliseren?

**Comment by nielsm5** [comment]
Het komt nu 342 keer voor in de xsd.

**Comment by mhdirkse** [comment]
We moeten "active" blijven opnemen in <xs:element> declaraties die geen type definitie extenden. Voor elementen die met een type referentie worden gemaakt kunnen we "active" binnen het type trekken. Het is niet zo moeilijk om elk type een "active" attribute te geven.

Ik zie een slimmere manier. File GroupCreator beslist wanneer er een declared group nodig is en weet wanneer daar een ancestor bij hoort. We kunnen in de callback een extra method introduceren die een declared group maakt. Die extra method doet hetzelfde als de bestaande method, maar voegt attribute active toe. Dit effect kan ook door een argument van het type "Runnable" mee te geven.

Het enige wat we nu overhouden zijn elementen die met een type definitie gemaakt worden maar "active" als enig attribute hebben. Voor deze types kunnen we "active" aan de element type definitie toevoegen, zodat we geen extra DeclaredAttributeGroup hoeven te maken, alleen om "active" te herbergen.
