### ISSUE TITLE
Element <DummyMessageLog> is not allowed within <SenderPipe>

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/frank-doc#61]
The strict XSD rejects a &lt;DummyMessageLog&gt; within a &lt;SenderPipe&gt;. See picture below.

![image](https://user-images.githubusercontent.com/6784732/148927086-589a0b06-c3c3-410f-996b-63a30aeb9508.png)

**Comment by gvanbrakel** [comment]
This is due to the DummyMessageLog being deprecated

**Comment by nielsm5** [comment]
The DummyMessageLog is no longer required to display the messagelog informatie in the console.
