### ISSUE TITLE
Introduce java annotation @Optional and javadoc tag @ff.optional

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#68]
Optional overrides any mandatory setting.
Example use case:
AbstractPipe.setName() will get a `@ff.mandatory` annotation
IWrapperPipe.setName() and IValidator.setName() will get a `@Optional` annotation  or a `@ff.optional` javadoc tag, to avoid having to set a name for wrappers and validators

**Comment by mhdirkse** [comment]
In the use case you explain Java annotation @Optional. What is the meaning of JavaDoc tag @ff.optional? Do they do the same or is there a difference?

**Comment by gvanbrakel** [comment]
They are meant to be the same

**Comment by mhdirkse** [comment]
Oh, I understand. I should have read issue #69 before writing...

**Comment by mhdirkse** [comment]
Please also consider PR https://github.com/ibissource/iaf/pull/2808.
