### ISSUE TITLE
Provide java annotation alternatives for javadoc tags

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#69]
For each of the javadoc tags used by the Frank!Doc, a java annotation should exist as an alternative:
@ff.mandatory <-> @MandatoryAttribute
@ff.default <-> @DefaultValue
@ff.optional <-> @OptionalAttribute
@deprecated <-> @Deprecated

This allows the parser to use these values too, and allows to override values without having to respecify the javadoc.

**Comment by mhdirkse** [comment]
You write: "... and allows to override values without having to respecify the javadoc". Do you mean that the JavaDoc tags should not be removed, because you do not want to have to replace all JavaDoc tags? Or is there something more to it?

**Comment by gvanbrakel** [comment]
> You write: "... and allows to override values without having to respecify the javadoc". Do you mean that the JavaDoc tags should not be removed, because you do not want to have to replace all JavaDoc tags? Or is there something more to it?

I expect it to possible that javadoc tags and java annotations can co-exist, like javadoc and the IbisDoc annotation can co-exist.
