### ISSUE TITLE
Version info in XSDs and Json

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/frank-doc#71]
To support https://github.com/ibissource/iaf/issues/2736, we would like to have version information in the XML Schema and in the json.
The version string itself (something like '7.7-RC1' or '7.7-20220209' or any other string) can be passed to the FrankDoc generator as a command line parameter at startup.
In the XML Schema's the version info can be stored in an annotation somewhere in the first lines of the file
For the JSON, a metadata field can be inserted, like:
```
  "metadata": { "version": "7.7-RC1" }
```
The metadata construct allows to add other information later

**Comment by mhdirkse** [comment]
I do not fully understand how to add the version information to the XSDs. I propose the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:annotation>
    <xs:appinfo>
      <version>7.7-SNAPSHOT</version>
    </xs:appinfo>
  </xs:annotation>
</xs:schema>
```

I tested that this example is a valid XML schema document. If you open it in VSCode, you do not see errors.
