### ISSUE TITLE
CI/CD should check that the build succeeds with log level TRACE

### ISSUE THREAD

**Issue by mhdirkse** [ibissource/frank-doc#95]
During the development of #94 I wanted to configure log level TRACE. That caused the build to fail. This failure is fixed in #94, but we do not want to allow such an issue on the master. I propose we add an extra GitHub workflow to build this project with log level TRACE. The job should clone this project, then modify log4j2.xml to configure log level TRACE and then the workflow should run the Maven build.

**Comment by mhdirkse** [comment]
We should add this to the existing GitHub actions job. We can make an extra appender in `log4j2.xml`.

**Comment by gvanbrakel** [comment]
It should not be necessary to modify log4j2.xml, overriding a property on the command line should be enough.

**Comment by nielsm5** [comment]
> It should not be necessary to modify log4j2.xml, overriding a property on the command line should be enough.

That depends on the configuration. If a composite config has been defined, this will work, but if it uses the default settings you're better off using the cmd line argument `log4j.configurationFile=xyz.xml,original-logfile.xml` to use 2 xml files (the project provided + a custom one).

**Comment by gvanbrakel** [comment]
I think that we should avoid adding tests for these non functionalities that are unlikely to go undetected.

**Comment by mhdirkse** [comment]
I think this non functional is likely to go undetected for a while. Usually the Frank!Doc logs with log level INFO. Only if there is an issue, the log level is adjusted temporarily to TRACE. We do this because with log level TRACE, processing the F!F sources results in more than 50000 log lines. We do not want to bump into additional issues if we want to debug something.

**Comment by nielsm5** [comment]
Je kan in de `log4j2.component.properties` de configuration files (zie oa `log4j.configurationFile`).
Bij meerdere waardes maakt Log4j een compound configuration aan, die alle log bestanden afgaat.
Je kan ook een `.xml` en een `.properties` bestand gebruiken, dan kan je zowel dmv properties de xml configuratie overschrijven.
